version: '3'

services:
  my-server:
    image: busybox
    command: sh -c 'while true; echo "Listerning..."; do nc -l -p 3000; done'
    networks:
      - my_network
    deploy:
      placement:
        constraints: [node.role == manager]

  my-client:
    image: busybox
    command: sh -c 'sleep 3 && while true; do date | nc my-server 3000; sleep 15; done'
    networks:
      - my_network

networks:
  my_network:
